# Proper Orthogonal Decomposition Example 1

Author: Katiana Kontolati \
Date: August 27, 2020

In this example, the Direct Proper Orthogonal Decomposition (POD) and Higher-order Singular Value Decomposition (HOSVD) methods are used to decompose a set of data and extract basis functions which can be used for the reconstruction of the solution.

Import the necessary libraries. Here we import standard libraries such as numpy, matplotlib, and we also import the POD class from UQpy.

In [1]:
%pylab inline
from UQpy.DimensionReduction import DirectPOD, SnapshotPOD, HOSVD
import time

Populating the interactive namespace from numpy and matplotlib


Input dataset in the form of a second order tensor consists of three snapshot solutions. Using the POD method we reconstruct the input dataset by keeping a predefined number of modes.

In [2]:
Data = np.zeros((3, 5, 3))

Data[ :, :, 0] = [
[0.9073,  1.7842,  2.1236, 1.1323, 1.6545],
[0.8924,  1.7753,  -0.6631, 0.5654, 2.1235],
[2.1488,  4.2495,  1.8260, 0.3423, 4.9801]]

Data[:, :, 1] = [
[0.7158,  1.6970,  -0.0740, 5.478, 1.0987],
[-0.4898,  -1.5077,  1.9103, 6.7121, 0.5334],
[0.3054,  0.3207,  2.1335, 1.1082, 5.5435]]

Data[:, :, 2] = [
[-0.3698,  0.0151,  1.4429, 2.5463, 6.9871],
[2.4288,  4.0337,  -1.7495, -0.5012, 1.7654],
[2.3753,  4.7146,  -0.2716, 1.6543, 0.9121]]

### POD

The Direct POD method is used to compute the reconstructed solutions and reduced-order solutions in the spatial dimension of the data. Full reconstruction is achieved when the number of modes chosen, equals the number of dimensions. 

In [3]:
start_time = time.time()

pod = DirectPOD(input_sol=Data, modes=1, verbose=True)
Data_reconstr, Data_reduced = pod.run()

UQpy: Successful execution of Direct POD!
Dataset reconstruction: 59.769%


Print the reconstructed dataset.

In [4]:
print('Reconstructed snapshot no.1:')
print(Data_reconstr[:,:,0])

if np.allclose(Data, Data_reconstr)==True:
    print('Input data and reconstructed data are identical.')

elapsed_time = time.time() - start_time
time.strftime("%H:%M:%S", time.gmtime(elapsed_time))
print('Elapsed time: ', round(elapsed_time,8))

Reconstructed snapshot no.1:
[[ 0.37169308  1.07447209  1.12166392  2.90766999  3.23915022]
 [ 0.95438509  1.46078201 -0.21356999  2.07037707  1.41936339]
 [ 1.56579651  3.0151097   1.12358846  1.01320396  3.54585821]]
Elapsed time:  0.00614905


### HOSVD

The Higher-order singular value decomposition (HOSVD) method is used for data reconstruction. In addition, the reduced data represent the reduced solutions in the spatial dimension of the data while the number of solutions spanshots is preserved.

In [5]:
start_time = time.time()

hosvd = HOSVD(input_sol=Data, reconstr_perc=90, verbose=True)
Data_reconstr, Data_reduced = hosvd.run(get_error=True)

UQpy: Successful execution of HOSVD!
Reduced-order reconstruction error: 0.000%


Print the reconstructed dataset.

In [6]:
print('Reconstructed snapshot no.1:')
print(Data_reconstr[:,:,0])

if np.allclose(Data,Data_reconstr)==True:
    print('Input data and reconstructed data are identical.')
    
elapsed_time = time.time() - start_time
time.strftime("%H:%M:%S", time.gmtime(elapsed_time))
print('Elapsed time: ', round(elapsed_time,8))

Reconstructed snapshot no.1:
[[ 0.9073  1.7842  2.1236  1.1323  1.6545]
 [ 0.8924  1.7753 -0.6631  0.5654  2.1235]
 [ 2.1488  4.2495  1.826   0.3423  4.9801]]
Input data and reconstructed data are identical.
Elapsed time:  0.00726986
