# Monte Carlo sampling

Author: Dimitris G. Giovanis,  
Date: June 20, 2018  
Last Modified: Dimitris G. Giovanis
Date: May 5, 2020  
UQpy Version 3.0

In this example, a Monte Carlo sampling is employed to generate samples utilizing the UQpy MCS class. 

Import the necessary libraries. Here we import standard libraries such as numpy and matplotlib, but also need to import the MCS class from UQpy.

In [1]:
from UQpy.SampleMethods import MCS
import numpy as np
import matplotlib.pyplot as plt
import time

In [2]:
from UQpy.Distributions import Normal, DistributionContinuous1D
dist1 = Normal(loc=0., scale=1.)
dist2 = Normal(loc=0., scale=1.)

x = MCS(dist_object=[dist1,dist2], nsamples=5, random_state=[1,3],  verbose=True)
print(x.samples)
print(x.samples.shape)

UQpy: Running Monte Carlo Sampling.
UQpy: Monte Carlo Sampling Complete.
[[ 1.62434536  1.78862847]
 [-0.61175641  0.43650985]
 [-0.52817175  0.09649747]
 [-1.07296862 -1.8634927 ]
 [ 0.86540763 -0.2773882 ]]
(5, 2)


In [3]:
print(x)
x.run(nsamples=2)
print(x.samples)
print(x.samples.shape)

UQpy: Running Monte Carlo Sampling.
UQpy: Monte Carlo Sampling Complete.
[[ 1.62434536  1.78862847]
 [-0.61175641  0.43650985]
 [-0.52817175  0.09649747]
 [-1.07296862 -1.8634927 ]
 [ 0.86540763 -0.2773882 ]
 [ 1.62434536  1.78862847]
 [-0.61175641  0.43650985]]
(7, 2)


In [9]:
x.transform_u01()
print(x.samplesU01)

[[0.94784894 0.96316267]
 [0.27034947 0.66876657]
 [0.29869007 0.53843726]
 [0.1416426  0.03119649]
 [0.80659245 0.39074102]
 [0.94784894 0.96316267]
 [0.27034947 0.66876657]]


In [10]:
from UQpy.Distributions import MVNormal
dist = MVNormal(mean=[1., 2.], cov=[[4., -0.9], [-0.9, 1.]])

x1 = MCS(dist_object=[dist,dist],  nsamples=5, random_state=[123,123],  verbose=True)
print(x1.samples)

UQpy: Running Monte Carlo Sampling.
UQpy: Monte Carlo Sampling Complete.
[[[ 3.38736185  2.23541269]
  [ 3.38736185  2.23541269]]

 [[ 0.08946208  0.8979547 ]
  [ 0.08946208  0.8979547 ]]

 [[ 2.53138343  3.06057229]
  [ 2.53138343  3.06057229]]

 [[ 5.72159837  0.30657467]
  [ 5.72159837  0.30657467]]

 [[-1.71534735  1.97285583]
  [-1.71534735  1.97285583]]]


In [ ]:
x1.run(nsamples=3)
print(x1.samples)

In [ ]:
x1.transform_u01()
print(x1.samplesU01)

In [ ]:
xa = MCS(dist_object=dist1, nsamples=5, random_state=4,  verbose=True)
print(xa.samples)
xa.run(nsamples=2)
print(xa.samples)
xa.transform_u01()
print(xa.samplesU01)

In [8]:
x2 = MCS(dist_object=[dist1, dist], nsamples=5, random_state=[123,None],  verbose=True)
print(x2.samples)
print(len(x2.samples))


UQpy: Running Monte Carlo Sampling.
UQpy: Monte Carlo Sampling Complete.
[[array([-1.0856306]) array([-0.83200198,  1.47575068])]
 [array([0.99734545]) array([0.12660467, 4.25853655])]
 [array([0.2829785]) array([1.45766791, 2.22319604])]
 [array([-1.50629471]) array([4.21709802, 1.36547484])]
 [array([-0.57860025]) array([-0.82195525,  3.32333297])]]
5


In [ ]:
x2.run(nsamples=2)
print(len(x2.samples))

In [ ]:
new_samples = x2.samples[:][1]

samples = np.zeros(shape=(len(x2.samples), len(x2.samples[1])))
for i in range(len(x2.samples)):
    samples[i, :] = x2.samples[i][1]
print(samples)
print(len(samples[0]))

In [ ]:
x3 = MCS(dist_object=[dist1, dist1], nsamples=5, random_state=[123,None],  verbose=True)
print(x3.samples)
print(len(x3.samples[0]))


In [ ]:
fig, ax = plt.subplots()
plt.title('MCS design')
plt.scatter(samples[:, 0], samples[:, 1])
ax.yaxis.grid(True)
ax.xaxis.grid(True)
plt.show()

In [ ]:
fig, ax = plt.subplots()
plt.title('Histogram:parameter #1')
plt.hist(x.samples[:, 0])
ax.yaxis.grid(True)
ax.xaxis.grid(True)

fig, ax = plt.subplots()
plt.title('Histogram:parameter #2')
plt.hist(x.samples[:, 1])
ax.yaxis.grid(True)
ax.xaxis.grid(True)
plt.show()

When the sample method is called, the new samples are automatically appended to the existing samples.

In [ ]:
from UQpy.Distributions import MVNormal
dist = MVNormal(mean=[1., 2.], cov=[[4., -0.9], [-0.9, 1.]])

x1 = MCS(dist_object=dist, nsamples=5, random_state=123, verbose=True)
print(x1.samples)

In [ ]:
print(np.shape(x.samples))
fig, ax = plt.subplots()
plt.title('MCS design')
plt.scatter(x1.samples[:, 0], x1.samples[:, 1], marker='o')
ax.yaxis.grid(True)
ax.xaxis.grid(True)
plt.show()

In [ ]:
x2 = MCS(dist_object=[dist1, dist], nsamples=5, random_state=123,  verbose=True)
#print(x2.samples)
print(np.array(x2.temp))

In [ ]:
from UQpy.Distributions import Binomial
dist3 = Binomial(n=5, p=0.4)
x3 = MCS(dist_object=[dist1, dist3], nsamples=5, verbose=True)

In [ ]:
print(np.shape(x.samples))
fig, ax = plt.subplots()
plt.title('MCS design')
plt.scatter(x3.samples[:, 0], x3.samples[:, 1], marker='o')
ax.yaxis.grid(True)
ax.xaxis.grid(True)
plt.show()

In [ ]:
x3.run(nsamples=100)

In [ ]:
print(x3.samples.shape[0])

In [11]:
from UQpy.Distributions import Normal, Lognormal, JointInd
marginals = [Normal(loc=2., scale=2.), Lognormal(s=1., loc=0., scale=np.exp(5))]
dist = JointInd(marginals=marginals)

In [13]:
from UQpy.SampleMethods import LHS
